version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: clyp
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}